
project:
  type: website

website:
  title: "Data-Driven (Multi-Objective) Bayesian Optimisation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: days/day1.qmd
        text: Day 1
      - href: days/day2.qmd
        text: Day 2
      - href: days/day3.qmd
        text: Day 3
      - href: days/day4.qmd
        text: Day 4
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: cosmo
    toc: true
